<?php

/**
 * Zaboy lib (http://zaboy.org/lib/)
 *
 * @copyright  Zaboychenko Andrey
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

namespace zaboy\test\rest\DataStore\Eav;

use zaboy\rest\DataStore\Eav\SysEntities;
use zaboy\rest\DataStore\Eav\SuperEntity;
use zaboy\rest\DataStore\Eav\Example\StoreCatalog;
use Xiag\Rql\Parser\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 16:19:25.
 */
class SuperEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SuperEntity
     */
    protected $object;

    /** @var  ContainerInterface */
    protected $container;

    protected function setUp()
    {
        $this->container = include 'config/container.php';
        $sysEntities = $this->container->get(SysEntities::TABLE_NAME);
        $sysEntities->deleteAll();
    }

    public function test__supertEntity()
    {
        $this->object = $this->container->get(StoreCatalog::PRODUCT_TABLE_NAME . SuperEntity::LEFT_JOIN . StoreCatalog::CATEGORY_TABLE_NAME);
        $this->assertEquals('', $this->object->getSqlQuery(new Query()));
    }

}
