<?php

namespace zaboy\test\Middlewares\Factory;

use zaboy\rest\Middlewares\Factory\StoreMiddlewareFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class StoreMiddlewareFactoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var zaboy\rest\Pipes\Factory\RestPipeFactory
     */
    protected $object;
    
    /**
     * @var Zend\Db\Adapter\Adapter
     */
    protected $adapter;   
    
    /**
     * @var ContainerInterface
     */
    protected $container;   
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->container = include './config/container.php';
        $this->object = new StoreMiddlewareFactory();
        $this->adapter = $this->container->get('db');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /*
     * @see test.global.php
     */
    public function testRestPipeFactoryAbstractFactory__canCreateIfConfigAbsent() {
        $requestedName = 'resource_name___';
        $this->setExpectedException('zaboy\rest\RestException');  
        $result = $this->object->__invoke($this->container, $requestedName);
    }


    /*
     * @see test.global.php'tablle_with_name_same_as_resource_name'
     */
    public function testRestPipeFactoryAbstractFactory__canCreateIfTableExist() {
        $tableName = 'table_with_name_same_as_resource_name';
        $createStatementStr = "CREATE TABLE IF NOT EXISTS $tableName (id INT)";
        $createStatement = $this->adapter->query($createStatementStr);
        var_dump($createStatement->execute());
        $result = $this->object->__invoke($this->container, $tableName); 
        $this->assertSame(
                true,
                $result  instanceof \Zend\Stratigility\MiddlewareInterface
        );
        $deleteStatementStr = "DROP TABLE IF EXISTS " .  $tableName;
        $deleteStatement = $this->adapter->query($deleteStatementStr);
        //$deleteStatement->execute();
        
    }

    
    
    /*
     * @see test.global.php
     */
    public function testRestPipeFactoryAbstractFactory__canCreateIfDataStorInConfigExist() {
        $tableName = 'table_for_db_data_store';
        $createStatementStr = "CREATE TABLE IF NOT EXISTS $tableName (id INT)";
        $createStatement = $this->adapter->query($createStatementStr);
        $createStatement->execute();
        $result = $this->object->__invoke($this->container, 'test_DataStoreDbTableWithNameAsResourceName'); 
        $this->assertSame(
                true,
                $result  instanceof \Zend\Stratigility\MiddlewareInterface
        );
        $deleteStatementStr = "DROP TABLE IF EXISTS " .  $tableName;
        $deleteStatement = $this->adapter->query($deleteStatementStr);
        $deleteStatement->execute();
    }    

    /*
     * @see test.global.php
     */
    public function testRestPipeFactoryAbstractFactory__canCreateIfMiddlewareInConfigExist() {
        $result = $this->object->__invoke($this->container, 'test_MiddlewareWithNameAsResourceName'); 
        $this->assertSame(
                true,
                $result  instanceof \Zend\Stratigility\MiddlewareInterface
        );
    }    
}
